package com.aibabel.scenic.utils;

/**
 * Created by fytworks on 2019/3/26.
 */

public class CityConfig {
    //亚洲
    public static final String asiaFragment = "{\n" +
            "    \"code\":\"1\",\n" +
            "    \"msg\":\"Success!\",\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"countryName\":\"中国台湾\",\n" +
            "            \"countryId\":\"CurrentCountryId89\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"台北\",\n" +
            "                    \"cityId\":\"CurrentCityId300\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"高雄\",\n" +
            "                    \"cityId\":\"CurrentCityId350\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"中国大陆\",\n" +
            "            \"countryId\":\"CurrentCountryId40\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"三亚市\",\n" +
            "                    \"cityId\":\"CurrentCityId415\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"三明市\",\n" +
            "                    \"cityId\":\"CurrentCityId444\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"上海\",\n" +
            "                    \"cityId\":\"CurrentCityId139\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"上饶市\",\n" +
            "                    \"cityId\":\"CurrentCityId468\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"丽江\",\n" +
            "                    \"cityId\":\"CurrentCityId427\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"九江市\",\n" +
            "                    \"cityId\":\"CurrentCityId478\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"介休市\",\n" +
            "                    \"cityId\":\"CurrentCityId470\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"伊春市\",\n" +
            "                    \"cityId\":\"CurrentCityId484\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"保定市\",\n" +
            "                    \"cityId\":\"CurrentCityId441\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"六安市\",\n" +
            "                    \"cityId\":\"CurrentCityId462\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"内蒙古大兴安岭\",\n" +
            "                    \"cityId\":\"CurrentCityId439\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"北京\",\n" +
            "                    \"cityId\":\"CurrentCityId135\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"南京\",\n" +
            "                    \"cityId\":\"CurrentCityId315\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"南宁\",\n" +
            "                    \"cityId\":\"CurrentCityId431\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"南平市\",\n" +
            "                    \"cityId\":\"CurrentCityId450\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"厦门\",\n" +
            "                    \"cityId\":\"CurrentCityId353\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"句容市\",\n" +
            "                    \"cityId\":\"CurrentCityId471\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"台州市\",\n" +
            "                    \"cityId\":\"CurrentCityId460\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"合肥市\",\n" +
            "                    \"cityId\":\"CurrentCityId425\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"哈尔滨市\",\n" +
            "                    \"cityId\":\"CurrentCityId417\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"唐山市\",\n" +
            "                    \"cityId\":\"CurrentCityId454\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"嘉兴市\",\n" +
            "                    \"cityId\":\"CurrentCityId449\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"大同市\",\n" +
            "                    \"cityId\":\"CurrentCityId434\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"大理\",\n" +
            "                    \"cityId\":\"CurrentCityId354\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"大连市\",\n" +
            "                    \"cityId\":\"CurrentCityId426\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"天津\",\n" +
            "                    \"cityId\":\"CurrentCityId371\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"宁德市\",\n" +
            "                    \"cityId\":\"CurrentCityId451\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"宁波\",\n" +
            "                    \"cityId\":\"CurrentCityId380\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"宁波市\",\n" +
            "                    \"cityId\":\"CurrentCityId488\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"安庆市\",\n" +
            "                    \"cityId\":\"CurrentCityId445\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"宜昌市\",\n" +
            "                    \"cityId\":\"CurrentCityId410\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"宣城市\",\n" +
            "                    \"cityId\":\"CurrentCityId479\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"常州市\",\n" +
            "                    \"cityId\":\"CurrentCityId455\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"常熟市\",\n" +
            "                    \"cityId\":\"CurrentCityId435\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"广州市\",\n" +
            "                    \"cityId\":\"CurrentCityId416\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"延边朝鲜族自治州\",\n" +
            "                    \"cityId\":\"CurrentCityId475\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"张家界\",\n" +
            "                    \"cityId\":\"CurrentCityId421\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"徐州\",\n" +
            "                    \"cityId\":\"CurrentCityId378\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"忻州市\",\n" +
            "                    \"cityId\":\"CurrentCityId458\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"成都\",\n" +
            "                    \"cityId\":\"CurrentCityId335\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"扬州\",\n" +
            "                    \"cityId\":\"CurrentCityId367\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"承德市\",\n" +
            "                    \"cityId\":\"CurrentCityId443\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"抚州市\",\n" +
            "                    \"cityId\":\"CurrentCityId467\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"拉萨\",\n" +
            "                    \"cityId\":\"CurrentCityId437\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"敦煌\",\n" +
            "                    \"cityId\":\"CurrentCityId336\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"无锡市\",\n" +
            "                    \"cityId\":\"CurrentCityId461\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"昆明\",\n" +
            "                    \"cityId\":\"CurrentCityId356\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"晋中市\",\n" +
            "                    \"cityId\":\"CurrentCityId472\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"晋城市\",\n" +
            "                    \"cityId\":\"CurrentCityId442\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"景德镇市\",\n" +
            "                    \"cityId\":\"CurrentCityId411\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"本溪市\",\n" +
            "                    \"cityId\":\"CurrentCityId480\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"杭州\",\n" +
            "                    \"cityId\":\"CurrentCityId307\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"枣庄市\",\n" +
            "                    \"cityId\":\"CurrentCityId463\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"桂林\",\n" +
            "                    \"cityId\":\"CurrentCityId420\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"武汉\",\n" +
            "                    \"cityId\":\"CurrentCityId372\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"沈阳市\",\n" +
            "                    \"cityId\":\"CurrentCityId429\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"泉州\",\n" +
            "                    \"cityId\":\"CurrentCityId452\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"济南市\",\n" +
            "                    \"cityId\":\"CurrentCityId414\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"深圳市\",\n" +
            "                    \"cityId\":\"CurrentCityId418\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"温州市\",\n" +
            "                    \"cityId\":\"CurrentCityId481\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"湖州市\",\n" +
            "                    \"cityId\":\"CurrentCityId465\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"烟台市\",\n" +
            "                    \"cityId\":\"CurrentCityId464\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"登封市\",\n" +
            "                    \"cityId\":\"CurrentCityId432\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"石家庄\",\n" +
            "                    \"cityId\":\"CurrentCityId447\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"神农架\",\n" +
            "                    \"cityId\":\"CurrentCityId423\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"福州市\",\n" +
            "                    \"cityId\":\"CurrentCityId409\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"福鼎市\",\n" +
            "                    \"cityId\":\"CurrentCityId473\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"绍兴市\",\n" +
            "                    \"cityId\":\"CurrentCityId482\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"舟山市\",\n" +
            "                    \"cityId\":\"CurrentCityId474\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"苏州\",\n" +
            "                    \"cityId\":\"CurrentCityId308\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"衢州市\",\n" +
            "                    \"cityId\":\"CurrentCityId456\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"西双版纳\",\n" +
            "                    \"cityId\":\"CurrentCityId428\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"西宁市\",\n" +
            "                    \"cityId\":\"CurrentCityId438\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"西安\",\n" +
            "                    \"cityId\":\"CurrentCityId313\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"贵阳市\",\n" +
            "                    \"cityId\":\"CurrentCityId424\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"连云港市\",\n" +
            "                    \"cityId\":\"CurrentCityId485\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"邯郸市\",\n" +
            "                    \"cityId\":\"CurrentCityId446\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"鄂尔多斯\",\n" +
            "                    \"cityId\":\"CurrentCityId433\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"重庆\",\n" +
            "                    \"cityId\":\"CurrentCityId430\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"金华\",\n" +
            "                    \"cityId\":\"CurrentCityId381\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"银川市\",\n" +
            "                    \"cityId\":\"CurrentCityId436\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"镇江\",\n" +
            "                    \"cityId\":\"CurrentCityId382\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"长春市\",\n" +
            "                    \"cityId\":\"CurrentCityId419\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"长沙\",\n" +
            "                    \"cityId\":\"CurrentCityId339\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"阿坝州\",\n" +
            "                    \"cityId\":\"CurrentCityId392\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"青岛市\",\n" +
            "                    \"cityId\":\"CurrentCityId412\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"鞍山市\",\n" +
            "                    \"cityId\":\"CurrentCityId466\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"鹰潭市\",\n" +
            "                    \"cityId\":\"CurrentCityId494\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"黄山市\",\n" +
            "                    \"cityId\":\"CurrentCityId408\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"龙岩市\",\n" +
            "                    \"cityId\":\"CurrentCityId453\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"中国澳门\",\n" +
            "            \"countryId\":\"CurrentCountryId98\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"澳门\",\n" +
            "                    \"cityId\":\"CurrentCityId298\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"中国香港\",\n" +
            "            \"countryId\":\"CurrentCountryId88\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"香港\",\n" +
            "                    \"cityId\":\"CurrentCityId299\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"以色列\",\n" +
            "            \"countryId\":\"CurrentCountryId36\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"提比利亚\",\n" +
            "                    \"cityId\":\"CurrentCityId492\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"特拉维夫\",\n" +
            "                    \"cityId\":\"CurrentCityId493\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"耶路撒冷\",\n" +
            "                    \"cityId\":\"CurrentCityId27\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"印度\",\n" +
            "            \"countryId\":\"CurrentCountryId18\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"印度文明\",\n" +
            "                    \"cityId\":\"CurrentCityId157\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"德里\",\n" +
            "                    \"cityId\":\"CurrentCityId63\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"斋普尔\",\n" +
            "                    \"cityId\":\"CurrentCityId67\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"阿格拉\",\n" +
            "                    \"cityId\":\"CurrentCityId62\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"印度尼西亚\",\n" +
            "            \"countryId\":\"CurrentCountryId82\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"巴厘岛\",\n" +
            "                    \"cityId\":\"CurrentCityId297\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"土耳其\",\n" +
            "            \"countryId\":\"CurrentCountryId17\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"伊斯坦布尔\",\n" +
            "                    \"cityId\":\"CurrentCityId68\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"卡帕多西亚\",\n" +
            "                    \"cityId\":\"CurrentCityId70\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"土耳其简介\",\n" +
            "                    \"cityId\":\"CurrentCityId73\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"安卡拉\",\n" +
            "                    \"cityId\":\"CurrentCityId309\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"安塔利亚\",\n" +
            "                    \"cityId\":\"CurrentCityId310\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"棉花堡\",\n" +
            "                    \"cityId\":\"CurrentCityId69\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"尼泊尔\",\n" +
            "            \"countryId\":\"CurrentCountryId38\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"加德满都\",\n" +
            "                    \"cityId\":\"CurrentCityId19\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"博卡拉\",\n" +
            "                    \"cityId\":\"CurrentCityId517\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"印度教天神\",\n" +
            "                    \"cityId\":\"CurrentCityId21\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"巴德岗\",\n" +
            "                    \"cityId\":\"CurrentCityId22\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"帕坦\",\n" +
            "                    \"cityId\":\"CurrentCityId20\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"蓝毗尼\",\n" +
            "                    \"cityId\":\"CurrentCityId23\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"斯里兰卡\",\n" +
            "            \"countryId\":\"CurrentCountryId85\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"斯里兰卡\",\n" +
            "                    \"cityId\":\"CurrentCityId306\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"新加坡\",\n" +
            "            \"countryId\":\"CurrentCountryId11\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"新加坡（城）\",\n" +
            "                    \"cityId\":\"CurrentCityId94\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"日本\",\n" +
            "            \"countryId\":\"CurrentCountryId8\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"东京\",\n" +
            "                    \"cityId\":\"CurrentCityId106\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"京都\",\n" +
            "                    \"cityId\":\"CurrentCityId107\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"冲绳\",\n" +
            "                    \"cityId\":\"CurrentCityId348\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"北九州市\",\n" +
            "                    \"cityId\":\"CurrentCityId168\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"北海道\",\n" +
            "                    \"cityId\":\"CurrentCityId114\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"名古屋\",\n" +
            "                    \"cityId\":\"CurrentCityId112\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"大阪\",\n" +
            "                    \"cityId\":\"CurrentCityId108\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"奈良\",\n" +
            "                    \"cityId\":\"CurrentCityId113\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"姬路\",\n" +
            "                    \"cityId\":\"CurrentCityId326\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"富士山\",\n" +
            "                    \"cityId\":\"CurrentCityId169\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"富良野\",\n" +
            "                    \"cityId\":\"CurrentCityId323\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"广岛\",\n" +
            "                    \"cityId\":\"CurrentCityId324\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"日本文化\",\n" +
            "                    \"cityId\":\"CurrentCityId109\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"日本简介\",\n" +
            "                    \"cityId\":\"CurrentCityId111\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"横滨\",\n" +
            "                    \"cityId\":\"CurrentCityId177\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"熊本\",\n" +
            "                    \"cityId\":\"CurrentCityId328\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"神户\",\n" +
            "                    \"cityId\":\"CurrentCityId176\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"福冈\",\n" +
            "                    \"cityId\":\"CurrentCityId170\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"箱根\",\n" +
            "                    \"cityId\":\"CurrentCityId291\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"镰仓\",\n" +
            "                    \"cityId\":\"CurrentCityId292\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"长崎\",\n" +
            "                    \"cityId\":\"CurrentCityId329\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"柬埔寨\",\n" +
            "            \"countryId\":\"CurrentCountryId19\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"暹粒\",\n" +
            "                    \"cityId\":\"CurrentCityId60\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"金边\",\n" +
            "                    \"cityId\":\"CurrentCityId61\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"泰国\",\n" +
            "            \"countryId\":\"CurrentCountryId20\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"普吉岛\",\n" +
            "                    \"cityId\":\"CurrentCityId171\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"曼谷\",\n" +
            "                    \"cityId\":\"CurrentCityId58\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"清莱\",\n" +
            "                    \"cityId\":\"CurrentCityId349\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"清迈\",\n" +
            "                    \"cityId\":\"CurrentCityId59\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"芭提雅\",\n" +
            "                    \"cityId\":\"CurrentCityId407\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"苏梅岛\",\n" +
            "                    \"cityId\":\"CurrentCityId406\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"老挝\",\n" +
            "            \"countryId\":\"CurrentCountryId93\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"万荣\",\n" +
            "                    \"cityId\":\"CurrentCityId399\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"万象\",\n" +
            "                    \"cityId\":\"CurrentCityId398\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"琅勃拉邦\",\n" +
            "                    \"cityId\":\"CurrentCityId397\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"菲律宾\",\n" +
            "            \"countryId\":\"CurrentCountryId94\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"马尼拉\",\n" +
            "                    \"cityId\":\"CurrentCityId413\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"越南\",\n" +
            "            \"countryId\":\"CurrentCountryId43\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"会安\",\n" +
            "                    \"cityId\":\"CurrentCityId174\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"河内\",\n" +
            "                    \"cityId\":\"CurrentCityId142\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"胡志明市\",\n" +
            "                    \"cityId\":\"CurrentCityId352\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"芽庄\",\n" +
            "                    \"cityId\":\"CurrentCityId351\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"阿联酋\",\n" +
            "            \"countryId\":\"CurrentCountryId28\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"迪拜\",\n" +
            "                    \"cityId\":\"CurrentCityId39\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"阿布扎比\",\n" +
            "                    \"cityId\":\"CurrentCityId40\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"韩国\",\n" +
            "            \"countryId\":\"CurrentCountryId9\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"南怡岛\",\n" +
            "                    \"cityId\":\"CurrentCityId440\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"济州岛\",\n" +
            "                    \"cityId\":\"CurrentCityId105\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"首尔\",\n" +
            "                    \"cityId\":\"CurrentCityId104\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"马来西亚\",\n" +
            "            \"countryId\":\"CurrentCountryId21\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"吉隆坡\",\n" +
            "                    \"cityId\":\"CurrentCityId55\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"朗卡维\",\n" +
            "                    \"cityId\":\"CurrentCityId387\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"槟城\",\n" +
            "                    \"cityId\":\"CurrentCityId56\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"沙巴亚庇\",\n" +
            "                    \"cityId\":\"CurrentCityId502\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"沙巴仙本那\",\n" +
            "                    \"cityId\":\"CurrentCityId505\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"马六甲\",\n" +
            "                    \"cityId\":\"CurrentCityId57\"\n" +
            "                }\n" +
            "            ]\n" +
            "        }\n" +
            "    ]\n" +
            "}";

    //欧洲
    public static final String euiopeFragment = "{\n" +
            "    \"code\":\"1\",\n" +
            "    \"msg\":\"Success!\",\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"countryName\":\"丹麦\",\n" +
            "            \"countryId\":\"CurrentCountryId23\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"丹麦简介\",\n" +
            "                    \"cityId\":\"CurrentCityId52\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"哥本哈根\",\n" +
            "                    \"cityId\":\"CurrentCityId49\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"奥胡斯\",\n" +
            "                    \"cityId\":\"CurrentCityId341\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"希勒勒\",\n" +
            "                    \"cityId\":\"CurrentCityId51\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"欧登塞\",\n" +
            "                    \"cityId\":\"CurrentCityId343\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"罗斯基勒\",\n" +
            "                    \"cityId\":\"CurrentCityId342\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"赫尔辛格\",\n" +
            "                    \"cityId\":\"CurrentCityId50\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"俄罗斯\",\n" +
            "            \"countryId\":\"CurrentCountryId31\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"下诺夫哥罗德\",\n" +
            "                    \"cityId\":\"CurrentCityId476\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"伊尔库茨克\",\n" +
            "                    \"cityId\":\"CurrentCityId389\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"伏尔加格勒\",\n" +
            "                    \"cityId\":\"CurrentCityId503\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"俄罗斯简介\",\n" +
            "                    \"cityId\":\"CurrentCityId490\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"加里宁格勒\",\n" +
            "                    \"cityId\":\"CurrentCityId486\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"叶卡捷琳堡\",\n" +
            "                    \"cityId\":\"CurrentCityId390\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"喀山\",\n" +
            "                    \"cityId\":\"CurrentCityId487\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"圣彼得堡\",\n" +
            "                    \"cityId\":\"CurrentCityId153\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"弗拉基米尔\",\n" +
            "                    \"cityId\":\"CurrentCityId388\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"符拉迪沃斯托克（海参葳）\",\n" +
            "                    \"cityId\":\"CurrentCityId393\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"索契\",\n" +
            "                    \"cityId\":\"CurrentCityId477\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"莫斯科\",\n" +
            "                    \"cityId\":\"CurrentCityId31\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"萨马拉\",\n" +
            "                    \"cityId\":\"CurrentCityId489\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"顿河畔罗斯托夫\",\n" +
            "                    \"cityId\":\"CurrentCityId506\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"克罗地亚\",\n" +
            "            \"countryId\":\"CurrentCountryId95\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"扎达尔\",\n" +
            "                    \"cityId\":\"CurrentCityId500\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"斯普利特\",\n" +
            "                    \"cityId\":\"CurrentCityId405\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"普拉\",\n" +
            "                    \"cityId\":\"CurrentCityId507\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"杜布罗夫尼克\",\n" +
            "                    \"cityId\":\"CurrentCityId501\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"萨格勒布\",\n" +
            "                    \"cityId\":\"CurrentCityId504\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"匈牙利\",\n" +
            "            \"countryId\":\"CurrentCountryId26\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"匈牙利简介\",\n" +
            "                    \"cityId\":\"CurrentCityId144\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"布达佩斯\",\n" +
            "                    \"cityId\":\"CurrentCityId44\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"奥地利\",\n" +
            "            \"countryId\":\"CurrentCountryId25\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"哈尔施塔特\",\n" +
            "                    \"cityId\":\"CurrentCityId337\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"因斯布鲁克\",\n" +
            "                    \"cityId\":\"CurrentCityId340\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"维也纳\",\n" +
            "                    \"cityId\":\"CurrentCityId45\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"萨尔茨堡\",\n" +
            "                    \"cityId\":\"CurrentCityId158\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"希腊\",\n" +
            "            \"countryId\":\"CurrentCountryId30\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"圣托里尼\",\n" +
            "                    \"cityId\":\"CurrentCityId345\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"希腊简介\",\n" +
            "                    \"cityId\":\"CurrentCityId35\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"扎金索斯\",\n" +
            "                    \"cityId\":\"CurrentCityId175\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"米克诺斯\",\n" +
            "                    \"cityId\":\"CurrentCityId33\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"罗德岛\",\n" +
            "                    \"cityId\":\"CurrentCityId34\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"雅典\",\n" +
            "                    \"cityId\":\"CurrentCityId32\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"德国\",\n" +
            "            \"countryId\":\"CurrentCountryId10\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"德国简介\",\n" +
            "                    \"cityId\":\"CurrentCityId102\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"慕尼黑\",\n" +
            "                    \"cityId\":\"CurrentCityId98\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"杜塞尔多夫\",\n" +
            "                    \"cityId\":\"CurrentCityId172\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"柏林\",\n" +
            "                    \"cityId\":\"CurrentCityId95\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"汉堡\",\n" +
            "                    \"cityId\":\"CurrentCityId101\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"法兰克福\",\n" +
            "                    \"cityId\":\"CurrentCityId100\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"海德堡\",\n" +
            "                    \"cityId\":\"CurrentCityId99\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"福森\",\n" +
            "                    \"cityId\":\"CurrentCityId96\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"科隆\",\n" +
            "                    \"cityId\":\"CurrentCityId97\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"意大利\",\n" +
            "            \"countryId\":\"CurrentCountryId6\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"佛罗伦萨\",\n" +
            "                    \"cityId\":\"CurrentCityId121\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"圣吉米尼亚诺\",\n" +
            "                    \"cityId\":\"CurrentCityId296\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"威尼斯\",\n" +
            "                    \"cityId\":\"CurrentCityId122\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"庞贝\",\n" +
            "                    \"cityId\":\"CurrentCityId386\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"意大利简介\",\n" +
            "                    \"cityId\":\"CurrentCityId137\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"意大利美食\",\n" +
            "                    \"cityId\":\"CurrentCityId126\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"比萨\",\n" +
            "                    \"cityId\":\"CurrentCityId124\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"米兰\",\n" +
            "                    \"cityId\":\"CurrentCityId123\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"索伦托\",\n" +
            "                    \"cityId\":\"CurrentCityId295\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"维罗纳\",\n" +
            "                    \"cityId\":\"CurrentCityId385\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"罗马\",\n" +
            "                    \"cityId\":\"CurrentCityId120\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"西西里\",\n" +
            "                    \"cityId\":\"CurrentCityId396\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"那不勒斯\",\n" +
            "                    \"cityId\":\"CurrentCityId191\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"锡耶纳\",\n" +
            "                    \"cityId\":\"CurrentCityId190\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"阿西西\",\n" +
            "                    \"cityId\":\"CurrentCityId294\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"挪威\",\n" +
            "            \"countryId\":\"CurrentCountryId96\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"卑尔根\",\n" +
            "                    \"cityId\":\"CurrentCityId469\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"奥斯陆\",\n" +
            "                    \"cityId\":\"CurrentCityId448\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"奥斯陆峡湾\",\n" +
            "                    \"cityId\":\"CurrentCityId459\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"捷克\",\n" +
            "            \"countryId\":\"CurrentCountryId33\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"克鲁姆洛夫（CK小镇）\",\n" +
            "                    \"cityId\":\"CurrentCityId496\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"卡罗维发利\",\n" +
            "                    \"cityId\":\"CurrentCityId495\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"布拉格\",\n" +
            "                    \"cityId\":\"CurrentCityId150\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"布杰约维采（CB小镇）\",\n" +
            "                    \"cityId\":\"CurrentCityId497\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"梵蒂冈\",\n" +
            "            \"countryId\":\"CurrentCountryId35\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"梵蒂冈简介\",\n" +
            "                    \"cityId\":\"CurrentCityId28\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"梵蒂冈（城）\",\n" +
            "                    \"cityId\":\"CurrentCityId159\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"比利时\",\n" +
            "            \"countryId\":\"CurrentCountryId22\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"安特卫普\",\n" +
            "                    \"cityId\":\"CurrentCityId312\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"布鲁塞尔\",\n" +
            "                    \"cityId\":\"CurrentCityId53\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"布鲁日\",\n" +
            "                    \"cityId\":\"CurrentCityId54\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"根特\",\n" +
            "                    \"cityId\":\"CurrentCityId311\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"法国\",\n" +
            "            \"countryId\":\"CurrentCountryId5\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"凡尔赛\",\n" +
            "                    \"cityId\":\"CurrentCityId17\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"卢瓦尔河谷\",\n" +
            "                    \"cityId\":\"CurrentCityId288\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"尼斯\",\n" +
            "                    \"cityId\":\"CurrentCityId302\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"巴黎\",\n" +
            "                    \"cityId\":\"CurrentCityId13\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"戛纳\",\n" +
            "                    \"cityId\":\"CurrentCityId303\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"普鲁旺斯\",\n" +
            "                    \"cityId\":\"CurrentCityId16\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"枫丹白露\",\n" +
            "                    \"cityId\":\"CurrentCityId18\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"法国简介\",\n" +
            "                    \"cityId\":\"CurrentCityId11\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"法国美食\",\n" +
            "                    \"cityId\":\"CurrentCityId127\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"阿维尼翁\",\n" +
            "                    \"cityId\":\"CurrentCityId14\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"马赛\",\n" +
            "                    \"cityId\":\"CurrentCityId15\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"波兰\",\n" +
            "            \"countryId\":\"CurrentCountryId42\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"克拉科夫\",\n" +
            "                    \"cityId\":\"CurrentCityId184\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"华沙\",\n" +
            "                    \"cityId\":\"CurrentCityId183\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"爱尔兰\",\n" +
            "            \"countryId\":\"CurrentCountryId48\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"都柏林\",\n" +
            "                    \"cityId\":\"CurrentCityId166\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"瑞典\",\n" +
            "            \"countryId\":\"CurrentCountryId49\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"斯德哥尔摩\",\n" +
            "                    \"cityId\":\"CurrentCityId178\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"瑞士\",\n" +
            "            \"countryId\":\"CurrentCountryId29\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"伯尔尼\",\n" +
            "                    \"cityId\":\"CurrentCityId162\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"卢塞恩\",\n" +
            "                    \"cityId\":\"CurrentCityId37\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"因特拉肯\",\n" +
            "                    \"cityId\":\"CurrentCityId36\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"日内瓦\",\n" +
            "                    \"cityId\":\"CurrentCityId164\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"瑞士简介\",\n" +
            "                    \"cityId\":\"CurrentCityId38\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"瑞士美食\",\n" +
            "                    \"cityId\":\"CurrentCityId151\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"苏黎世\",\n" +
            "                    \"cityId\":\"CurrentCityId165\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"芬兰\",\n" +
            "            \"countryId\":\"CurrentCountryId81\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"罗瓦涅米\",\n" +
            "                    \"cityId\":\"CurrentCityId403\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"赫尔辛基\",\n" +
            "                    \"cityId\":\"CurrentCityId289\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"英国\",\n" +
            "            \"countryId\":\"CurrentCountryId7\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"伦敦\",\n" +
            "                    \"cityId\":\"CurrentCityId116\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"剑桥\",\n" +
            "                    \"cityId\":\"CurrentCityId118\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"圣安德鲁斯\",\n" +
            "                    \"cityId\":\"CurrentCityId384\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"威尔特郡\",\n" +
            "                    \"cityId\":\"CurrentCityId402\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"巴斯\",\n" +
            "                    \"cityId\":\"CurrentCityId304\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"斯特灵\",\n" +
            "                    \"cityId\":\"CurrentCityId383\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"爱丁堡\",\n" +
            "                    \"cityId\":\"CurrentCityId117\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"牛津\",\n" +
            "                    \"cityId\":\"CurrentCityId119\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"英国简介\",\n" +
            "                    \"cityId\":\"CurrentCityId115\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"荷兰\",\n" +
            "            \"countryId\":\"CurrentCountryId27\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"海牙\",\n" +
            "                    \"cityId\":\"CurrentCityId42\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"荷兰简介\",\n" +
            "                    \"cityId\":\"CurrentCityId43\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"阿姆斯特丹\",\n" +
            "                    \"cityId\":\"CurrentCityId41\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"葡萄牙\",\n" +
            "            \"countryId\":\"CurrentCountryId37\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"波尔图\",\n" +
            "                    \"cityId\":\"CurrentCityId25\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"葡萄牙简介\",\n" +
            "                    \"cityId\":\"CurrentCityId148\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"辛特拉\",\n" +
            "                    \"cityId\":\"CurrentCityId26\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"里斯本\",\n" +
            "                    \"cityId\":\"CurrentCityId24\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"西班牙\",\n" +
            "            \"countryId\":\"CurrentCountryId16\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"塞哥维亚\",\n" +
            "                    \"cityId\":\"CurrentCityId78\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"塞维利亚\",\n" +
            "                    \"cityId\":\"CurrentCityId76\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"巴塞罗那\",\n" +
            "                    \"cityId\":\"CurrentCityId75\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"托莱多\",\n" +
            "                    \"cityId\":\"CurrentCityId79\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"格拉纳达\",\n" +
            "                    \"cityId\":\"CurrentCityId77\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"瓦伦西亚\",\n" +
            "                    \"cityId\":\"CurrentCityId394\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"科尔多瓦\",\n" +
            "                    \"cityId\":\"CurrentCityId80\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"西班牙简介\",\n" +
            "                    \"cityId\":\"CurrentCityId82\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"阿维拉\",\n" +
            "                    \"cityId\":\"CurrentCityId81\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"马德里\",\n" +
            "                    \"cityId\":\"CurrentCityId74\"\n" +
            "                }\n" +
            "            ]\n" +
            "        }\n" +
            "    ]\n" +
            "}";

    //非洲
    public static final String africaFragment ="{\n" +
            "    \"code\":\"1\",\n" +
            "    \"msg\":\"Success!\",\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"countryName\":\"埃及\",\n" +
            "            \"countryId\":\"CurrentCountryId47\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"亚历山大\",\n" +
            "                    \"cityId\":\"CurrentCityId359\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"卢克索\",\n" +
            "                    \"cityId\":\"CurrentCityId358\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"埃及简介\",\n" +
            "                    \"cityId\":\"CurrentCityId373\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"开罗\",\n" +
            "                    \"cityId\":\"CurrentCityId347\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"摩洛哥\",\n" +
            "            \"countryId\":\"CurrentCountryId24\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"达尔贝达（卡萨布兰卡）\",\n" +
            "                    \"cityId\":\"CurrentCityId47\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"马拉喀什\",\n" +
            "                    \"cityId\":\"CurrentCityId46\"\n" +
            "                }\n" +
            "            ]\n" +
            "        }\n" +
            "    ]\n" +
            "}";

    //北美洲
    public static final String northFragment ="{\n" +
            "    \"code\":\"1\",\n" +
            "    \"msg\":\"Success!\",\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"countryName\":\"加拿大\",\n" +
            "            \"countryId\":\"CurrentCountryId50\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"尼亚加拉瀑布城\",\n" +
            "                    \"cityId\":\"CurrentCityId317\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"温哥华\",\n" +
            "                    \"cityId\":\"CurrentCityId316\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"墨西哥\",\n" +
            "            \"countryId\":\"CurrentCountryId97\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"坎昆\",\n" +
            "                    \"cityId\":\"CurrentCityId512\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"墨西哥城\",\n" +
            "                    \"cityId\":\"CurrentCityId516\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"奇琴伊察\",\n" +
            "                    \"cityId\":\"CurrentCityId511\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"特奥蒂瓦坎\",\n" +
            "                    \"cityId\":\"CurrentCityId514\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"瓜纳华托\",\n" +
            "                    \"cityId\":\"CurrentCityId515\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"美国\",\n" +
            "            \"countryId\":\"CurrentCountryId12\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"加利福利亚\",\n" +
            "                    \"cityId\":\"CurrentCityId93\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"华盛顿\",\n" +
            "                    \"cityId\":\"CurrentCityId365\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"拉斯维加斯\",\n" +
            "                    \"cityId\":\"CurrentCityId140\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"旧金山\",\n" +
            "                    \"cityId\":\"CurrentCityId364\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"波士顿\",\n" +
            "                    \"cityId\":\"CurrentCityId363\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"波特兰\",\n" +
            "                    \"cityId\":\"CurrentCityId143\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"洛杉矶\",\n" +
            "                    \"cityId\":\"CurrentCityId361\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"纽约\",\n" +
            "                    \"cityId\":\"CurrentCityId362\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"美国简介\",\n" +
            "                    \"cityId\":\"CurrentCityId377\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"菲尼克斯\",\n" +
            "                    \"cityId\":\"CurrentCityId152\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"蒙特雷\",\n" +
            "                    \"cityId\":\"CurrentCityId141\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"西雅图\",\n" +
            "                    \"cityId\":\"CurrentCityId91\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"黄石国家公园\",\n" +
            "                    \"cityId\":\"CurrentCityId360\"\n" +
            "                }\n" +
            "            ]\n" +
            "        }\n" +
            "    ]\n" +
            "}";

    //南美洲
    public static final String southFragment ="{\n" +
            "    \"code\":\"1\",\n" +
            "    \"msg\":\"Success!\",\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"countryName\":\"巴西\",\n" +
            "            \"countryId\":\"CurrentCountryId15\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"圣保罗州\",\n" +
            "                    \"cityId\":\"CurrentCityId154\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"里约热内卢\",\n" +
            "                    \"cityId\":\"CurrentCityId85\"\n" +
            "                }\n" +
            "            ]\n" +
            "        }\n" +
            "    ]\n" +
            "}";

    //大洋洲
    public static final String oceaniaFragment ="{\n" +
            "    \"code\":\"1\",\n" +
            "    \"msg\":\"Success!\",\n" +
            "    \"data\":[\n" +
            "        {\n" +
            "            \"countryName\":\"新西兰\",\n" +
            "            \"countryId\":\"CurrentCountryId51\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"奥克兰\",\n" +
            "                    \"cityId\":\"CurrentCityId182\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"皇后镇\",\n" +
            "                    \"cityId\":\"CurrentCityId185\"\n" +
            "                }\n" +
            "            ]\n" +
            "        },\n" +
            "        {\n" +
            "            \"countryName\":\"澳大利亚\",\n" +
            "            \"countryId\":\"CurrentCountryId13\",\n" +
            "            \"cityMsg\":[\n" +
            "                {\n" +
            "                    \"cityName\":\"墨尔本\",\n" +
            "                    \"cityId\":\"CurrentCityId187\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"悉尼\",\n" +
            "                    \"cityId\":\"CurrentCityId87\"\n" +
            "                },\n" +
            "                {\n" +
            "                    \"cityName\":\"黄金海岸\",\n" +
            "                    \"cityId\":\"CurrentCityId188\"\n" +
            "                }\n" +
            "            ]\n" +
            "        }\n" +
            "    ]\n" +
            "}";

}
